# IFID_STATE: eyJzb3VyY2VzIjpbeyJpZCI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsIm5hbWUiOiJtaWxrIiwidHlwZSI6ImRhaXJ5IiwiaXNfYWxsZXJnZW4iOnRydWUsImlzX2RlY2xhcmFibGUiOnRydWV9XSwiZm9ybXMiOlt7ImlkIjoid2hleSIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9LHsiaWQiOiJ3cGMiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoiY3VyZCIsIm1hdHRlcl9zdGF0ZSI6InNlbWlfc29saWQifSx7ImlkIjoiZ2hlZSIsIm1hdHRlcl9zdGF0ZSI6InNlbWlfc29saWQifSx7ImlkIjoia2hvYSIsIm1hdHRlcl9zdGF0ZSI6InNlbWlfc29saWQifSx7ImlkIjoiY3JlYW0iLCJtYXR0ZXJfc3RhdGUiOiJ2aXNjb3VzIn0seyJpZCI6ImJ1dHRlciIsIm1hdHRlcl9zdGF0ZSI6InNlbWlfc29saWQifSx7ImlkIjoiY2hlZXNlIiwibWF0dGVyX3N0YXRlIjoic2VtaV9zb2xpZCJ9LHsiaWQiOiJwYW5lZXIiLCJtYXR0ZXJfc3RhdGUiOiJzZW1pX3NvbGlkIn0seyJpZCI6InlvZ2h1cnQiLCJtYXR0ZXJfc3RhdGUiOiJzZW1pX3NvbGlkIn0seyJpZCI6ImNvd19taWxrIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6InNvdXJfY3JlYW0iLCJtYXR0ZXJfc3RhdGUiOiJ2aXNjb3VzIn0seyJpZCI6InNtcF9wb3dkZXIiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoibWlsa19wb3dkZXIiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoiY2FzZWluIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6InRvbmVkX21pbGsiLCJtYXR0ZXJfc3RhdGUiOiJsaXF1aWQifSx7ImlkIjoic3dlZXRfd2hleSIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9LHsiaWQiOiJ3aGl0ZV9idXR0ZXIiLCJtYXR0ZXJfc3RhdGUiOiJzZW1pX3NvbGlkIn0seyJpZCI6Im1pbGtfcHJvdGVpbiIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9LHsiaWQiOiJ3aGV5X3BlcHRpZGVzIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6ImNoZWVzZV9wb3dkZXIiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoieW9ndXJ0X3Bvd2RlciIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJyZW5uZXRfY2FzZWluIiwibWF0dGVyX3N0YXRlIjoicG93ZGVyIn0seyJpZCI6ImN1bHR1cmVkX2NyZWFtIiwibWF0dGVyX3N0YXRlIjoidmlzY291cyJ9LHsiaWQiOiJkb3VibGVfdG9uZWRfbWlsayIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9XSwicmVsYXRpb25zIjpbeyJpZCI6IjgyY2JmMTk2LWRmOWMtNDI5Yi04YzBjLTdkNGM3MjE4NWJkYyIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoid2hleSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjb2FndWxhdGlvbiJdfSx7ImlkIjoiNDk1Mzk5N2QtODYzNS00YmVhLWJmMjEtY2JiZDQ5MDZlN2IxIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6IndoZXkiLCJmb3JtIjoid3BjIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbInVsdHJhZmlsdHJhdGlvbiIsImRyeWluZy1zcHJheSJdfSx7ImlkIjoiZTc0N2NlNWItMWEzYy00ODZiLTllY2YtNmRjZGIzYzU1YTJiIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJjdXJkIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImZlcm1lbnRhdGlvbiIsImNvYWd1bGF0aW9uIl19LHsiaWQiOiI1OWQ0YjdjNC0yNzNmLTQ2ZTUtYjViNS1iMzE1Nzg5N2JlNmUiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYnV0dGVyIiwiZm9ybSI6ImdoZWUiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY2xhcmlmaWNhdGlvbiJdfSx7ImlkIjoiNzdjNTE5YjMtNzhmNC00NGY4LThmMTktNTJhMmNjNjM5NTA2IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJraG9hIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImV2YXBvcmF0aW9uIl19LHsiaWQiOiI2YmUzMzNlNy04YWQwLTQzMmItYTExNy1hOWNkM2UyNzI2ODMiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6ImNyZWFtIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImNlbnRyaWZ1Z2F0aW9uIl19LHsiaWQiOiI1OGNjZjVlMC1jNzI0LTQ1ZGItYWQyNS0xZWQ0YTNlZjA0NTYiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiY3JlYW0iLCJmb3JtIjoiYnV0dGVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImNodXJuaW5nIl19LHsiaWQiOiI3MWRiNGZmYS1jZDU0LTRjZjYtOGY4Mi00ZjAyZDMyODdjYTYiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6ImNoZWVzZSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjb2FndWxhdGlvbiIsImZlcm1lbnRhdGlvbiJdfSx7ImlkIjoiNzEyOWM4MzUtZWNkOC00MmExLWExMTUtODUxMzViODljMWNiIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJwYW5lZXIiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY29hZ3VsYXRpb24iXX0seyJpZCI6ImQwMmEwZGViLTkwZjYtNGVlMS04ODI3LTJiNjI4ZDhjOGRlNCIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoieW9naHVydCIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJmZXJtZW50YXRpb24iXX0seyJpZCI6ImQ0Mzk3MTJlLTlkMjItNDA4Zi1hYTk0LWE1OTdiYmNiNDYzNyIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjcmVhbSIsImZvcm0iOiJzb3VyX2NyZWFtIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImNlbnRyaWZ1Z2F0aW9uIiwiZmVybWVudGF0aW9uIl19LHsiaWQiOiIyYzE3NTJkMi1iNTNkLTRiZTYtYTY3Ni01OTg3MDcxZGQ5ZjkiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6InNtcF9wb3dkZXIiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsic2tpbW1pbmciLCJkcnlpbmctc3ByYXkiXX0seyJpZCI6IjJhZGM2Y2ZhLTFjODAtNGU1ZS05M2RiLWFhMTQ4Y2FmZjBhMiIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoibWlsa19wb3dkZXIiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiZHJ5aW5nLXNwcmF5Il19LHsiaWQiOiIzMTZkZWViYi05ZTJkLTQ4NmEtYmNkNy1mZDg0ZDg5OTg4MTgiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6ImNhc2VpbiIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjb2FndWxhdGlvbiJdfSx7ImlkIjoiMTljYWVkYzMtMTFjNS00N2QwLWE1ZGEtYjU0YjVmOTQ3NmNiIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJ0b25lZF9taWxrIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbInN0YW5kYXJkaXphdGlvbiJdfSx7ImlkIjoiYTA0YTY2ZTItZWMzOC00MzhkLWE4MTMtZDQzMWY0MWQyYjk4IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6IndoZXkiLCJmb3JtIjoic3dlZXRfd2hleSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjb2FndWxhdGlvbiJdfSx7ImlkIjoiMmY0MTRiNDYtZWFmZi00Y2MwLWIwMzUtMjYwNGIxMGVjOTdiIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNyZWFtIiwiZm9ybSI6IndoaXRlX2J1dHRlciIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjaHVybmluZyJdfSx7ImlkIjoiZGMyY2I2MzctMmYyMi00ZDZhLWFiZWQtMmFhMmY1NDYwZmUwIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJtaWxrX3Byb3RlaW4iLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiZmlsdHJhdGlvbiJdfSx7ImlkIjoiOGZkMDBhZjQtYTU2Zi00MTVjLTgyNTgtZGRmZTRlNTgyOTJhIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6IndoZXkiLCJmb3JtIjoid2hleV9wZXB0aWRlcyIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJoeWRyb2x5c2lzIl19LHsiaWQiOiJjODUwZmYzZi03ZWNhLTQ2ZjctYmRkMi0xYjIxYmNjMDM4ZTUiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiY2hlZXNlIiwiZm9ybSI6ImNoZWVzZV9wb3dkZXIiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiZHJ5aW5nLXNwcmF5Il19LHsiaWQiOiI5NTViOWQ2Yi0xZTViLTQ3MTUtOTYzYS0xOGFiYjdkODk3OTAiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoieW9naHVydCIsImZvcm0iOiJ5b2d1cnRfcG93ZGVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImRyeWluZy1zcHJheSJdfSx7ImlkIjoiNDllNWI4ZmItYWJlOC00MWEzLTk2YmEtYmNjNzg0NTdmMWIxIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNhc2VpbiIsImZvcm0iOiJyZW5uZXRfY2FzZWluIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImRyeWluZy1zcHJheSJdfSx7ImlkIjoiMDRiZTNjOWMtNWZiYi00NDJiLWJmZTktMjY4MWQ4YWZiMjVkIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNyZWFtIiwiZm9ybSI6ImN1bHR1cmVkX2NyZWFtIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImZlcm1lbnRhdGlvbiJdfSx7ImlkIjoiMjE5MmQxZmUtZTY5NC00MjBjLThiMGMtMTQxYTczYWJlNTAxIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJkb3VibGVfdG9uZWRfbWlsayIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJzdGFuZGFyZGl6YXRpb24iXX1dLCJjdXN0b21NZXRob2RzIjpbImNlbnRyaWZ1Z2F0aW9uIiwic3RhbmRhcmRpemF0aW9uIiwiZmlsdHJhdGlvbiIsImh5ZHJvbHlzaXMiXSwiY3VzdG9tTWF0dGVyU3RhdGVzIjpbInZpc2NvdXMiXSwiY3VzdG9tU291cmNlVHlwZXMiOltdfQ==

# ── New enum values — add these to enum_requests.md ──────────────────
# NEW  processing_method: "centrifugation"
# NEW  processing_method: "standardization"
# NEW  processing_method: "filtration"
# NEW  processing_method: "hydrolysis"
# NEW  matter_state: "viscous"
# ─────────────────────────────────────────────────────────────────────

from index import Database, Source, IngredientForm, FormOf, VarietyOf

db = Database()

milk = db.add(Source(
    name="milk",
    type="dairy",
    is_allergen=True,
    is_declarable=True
))
db.relate(FormOf(origin=milk, form=whey, processing_method=["coagulation"]))
db.relate(FormOf(origin=milk, form=curd, processing_method=["fermentation", "coagulation"]))
db.relate(FormOf(origin=milk, form=khoa, processing_method=["evaporation"]))
db.relate(FormOf(origin=milk, form=cream, processing_method=["centrifugation"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=cheese, processing_method=["coagulation", "fermentation"]))
db.relate(FormOf(origin=milk, form=paneer, processing_method=["coagulation"]))
db.relate(FormOf(origin=milk, form=yoghurt, processing_method=["fermentation"]))
db.relate(FormOf(origin=milk, form=smp_powder, processing_method=["skimming", "drying-spray"]))
db.relate(FormOf(origin=milk, form=milk_powder, processing_method=["drying-spray"]))
db.relate(FormOf(origin=milk, form=casein, processing_method=["coagulation"]))
db.relate(FormOf(origin=milk, form=toned_milk, processing_method=["standardization"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=milk_protein, processing_method=["filtration"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=double_toned_milk, processing_method=["standardization"]))  # NEW processing_method

whey = db.add(IngredientForm(id="whey", matter_state="liquid"))
db.relate(FormOf(origin=whey, form=wpc, processing_method=["ultrafiltration", "drying-spray"]))
db.relate(FormOf(origin=whey, form=sweet_whey, processing_method=["coagulation"]))
db.relate(FormOf(origin=whey, form=whey_peptides, processing_method=["hydrolysis"]))  # NEW processing_method

wpc = db.add(IngredientForm(id="wpc", matter_state="powder"))

curd = db.add(IngredientForm(id="curd", matter_state="semi_solid"))

cream = db.add(IngredientForm(id="cream", matter_state="viscous"))  # NEW matter_state
db.relate(FormOf(origin=cream, form=butter, processing_method=["churning"]))
db.relate(FormOf(origin=cream, form=sour_cream, processing_method=["centrifugation", "fermentation"]))  # NEW processing_method
db.relate(FormOf(origin=cream, form=white_butter, processing_method=["churning"]))
db.relate(FormOf(origin=cream, form=cultured_cream, processing_method=["fermentation"]))

butter = db.add(IngredientForm(id="butter", matter_state="semi_solid"))
db.relate(FormOf(origin=butter, form=ghee, processing_method=["clarification"]))

ghee = db.add(IngredientForm(id="ghee", matter_state="semi_solid"))

khoa = db.add(IngredientForm(id="khoa", matter_state="semi_solid"))

cheese = db.add(IngredientForm(id="cheese", matter_state="semi_solid"))
db.relate(FormOf(origin=cheese, form=cheese_powder, processing_method=["drying-spray"]))

paneer = db.add(IngredientForm(id="paneer", matter_state="semi_solid"))

yoghurt = db.add(IngredientForm(id="yoghurt", matter_state="semi_solid"))
db.relate(FormOf(origin=yoghurt, form=yogurt_powder, processing_method=["drying-spray"]))

cow_milk = db.add(IngredientForm(id="cow_milk", matter_state="liquid"))

sour_cream = db.add(IngredientForm(id="sour_cream", matter_state="viscous"))  # NEW matter_state

smp_powder = db.add(IngredientForm(id="smp_powder", matter_state="powder"))

milk_powder = db.add(IngredientForm(id="milk_powder", matter_state="powder"))

casein = db.add(IngredientForm(id="casein", matter_state="liquid"))
db.relate(FormOf(origin=casein, form=rennet_casein, processing_method=["drying-spray"]))

toned_milk = db.add(IngredientForm(id="toned_milk", matter_state="liquid"))

sweet_whey = db.add(IngredientForm(id="sweet_whey", matter_state="liquid"))

white_butter = db.add(IngredientForm(id="white_butter", matter_state="semi_solid"))

milk_protein = db.add(IngredientForm(id="milk_protein", matter_state="liquid"))

whey_peptides = db.add(IngredientForm(id="whey_peptides", matter_state="liquid"))

cheese_powder = db.add(IngredientForm(id="cheese_powder", matter_state="powder"))

yogurt_powder = db.add(IngredientForm(id="yogurt_powder", matter_state="powder"))

rennet_casein = db.add(IngredientForm(id="rennet_casein", matter_state="powder"))

cultured_cream = db.add(IngredientForm(id="cultured_cream", matter_state="viscous"))  # NEW matter_state

double_toned_milk = db.add(IngredientForm(id="double_toned_milk", matter_state="liquid"))

print(db)